apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: env
    envs:
      - env.env

resources:
  - ../../base

replacements:
  - source:
      kind: ConfigMap
      name: env
      fieldPath: data.HOST
    targets:
      - select:
          kind: Ingress
          name: demo-app
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
      - select:
          kind: Certificate
          name: demo-app
        fieldPaths:
          - spec.dnsNames.0
